### PR TITLE
Application id per build

### PR DESCRIPTION
**Pull request by pnemonic78**

### CODE REVIEW

**Comment by Kaligula0** [comment]
Isn't it a (partial) duplicate of #84?

**Comment by Kaligula0** [comment]
Yeah, what I see is that #84 is 100% included in this #102.

**Review by djbrown — APPROVED** [review]
yes, the commits on #84 were replaced (force pushed) with a single commit which happens to also be the first commit of this PR.

LGTM - but that might break CI (more than it already is)
you may merge and I'll fix firebase and pipeline setup afterwards.

@pnemonic78 @Kaligula0 did you read my https://github.com/GnuCash-Pocket/gnucash-android/pull/84#issuecomment-2073018462?
I feel kinda stuck in regards of an official playstore release.
should we just use the already existing pnemonic account?
I'm also thinking about sharing admin access to the github org and google cloud/firebase project to both of you.

**Comment by pnemonic78** [comment]
I prefer to keep ".pnemonic" personal.
It is better to have some sort of official "org.gnucash.pocket" application registered somehow...

**Comment by Kaligula0** [comment]
> @pnemonic78 @Kaligula0 did you read my [#84 (comment)](https://github.com/GnuCash-Pocket/gnucash-android/pull/84#issuecomment-2073018462)? I feel kinda stuck in regards of an official playstore release. should we just use the already existing pnemonic account? I'm also thinking about sharing admin access to the github org and google cloud/firebase project to both of you.

Yeah, I saw that comment a few times, and I am sorry for late reply, but each time I didn't have the answer. I am also overwhelmed by the difficulty of registering organization developer account on Play Store. The payment of 25 bucks is not the biggest problem. Address, phone number, official registration… I have no idea how to do it in best way. Does anybody know of a similar case? Someone we can get in touch to ask how they managed to share such app?

As for the admin rights – I'm not sure I'm the right person. I try to be up to date with the repo, but I'm a hobby dev, and I can do only simple bug fixes in Android. I'm also not familiar with GH Actions and CI, that's why I am not able to fix it nor decide about it. Nevertheless, I try to keep up with the changes, issues and discussions.

**Review by djbrown — APPROVED** [review]

**Review by djbrown — DISMISSED** [review]

**Review by Kaligula0 — APPROVED** [review]

**Pull request merged**
